### Create credentials
POST http://localhost:9003/user
Content-Type: application/json

{
  "password": "hgsqddhgvhjed",
  "email": "tghjdjhdjhdjhdjhdest",
  "birthDate": "2007-12-03",
  "firstname": "azertyy",
  "lastname": "azerty",
  "idClub": 2
}

### Connect user
POST http://localhost:9003//authentication/connect
Content-Type: application/json

{
  "email": "tghjdjhdjhdjhdjhdest",
  "password": "hgsqddhgvhjed"
}